spring.application.name=rewardz
logging.level.org.springframework.core.io.support=OFF
logging.level.org.springframework.context.annotation=OFF

# Database Configuration
spring.datasource.url=jdbc:postgresql://postgres:5433/rewardzdb
spring.datasource.username=rewardzuser
spring.datasource.password=rewardzpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# JPA / Hibernate
#updates the database schema automatically
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
spring.jpa.show-sql=false

# Server Port
server.port=8080